services:

  web:
    image: imhero/healthcheck:latest
    container_name: imhero-web
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

#    env_file:
#      - .env
#    build:
#      context: .
#      dockerfile: dockerfile