# github-action/marketplace/Gradle-Build-Action
name: Run Gradle on PRs

on: [pull_request]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build


# github-actions에서 하는 java-ci-with-gradle
# name: Java CI

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 11
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'corretto'
#       - name: Validate Gradle wrapper
#         uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
#       - name: Build with Gradle
#         uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
#         with:
#           arguments: build
